# This is the Gradle build system for JVM applications.
# https://gradle.org/
# https://github.com/gradle/gradle
image: gradle:4.9-jdk8-alpine

variables:
  # Disable the Gradle daemon for Continuous Integration servers as correctness
  # is usually a priority over speed in CI environments. Using a fresh runtime
  # for each build is more reliable since the runtime is completely isolated
  # from any previous builds.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  # Set the location of the dependency cache to a local directory, so that it
  # can be cached between GitLab CI/CD jobs.
  GRADLE_USER_HOME: '.gradle'

build:
  stage: build
  script: gradle assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
    - .gradle


test:
  stage: test
  script: gradle check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
    - .gradle


license_management:
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  stage: test
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export LICENSE_MANAGEMENT_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --volume "$PWD:/code"
        "registry.gitlab.com/gitlab-org/security-products/license-management:$LICENSE_MANAGEMENT_VERSION" analyze /code
  artifacts:
    paths: [gl-license-management-report.json]
